name: 'gel2mdt-north-thames-prod'

services:
  redis:
    image: "redis:alpine"
    restart: always
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8002:8002"
      - "8004:8004"
    volumes:
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d
      - ./Docker/nginx/ssl/:/etc/nginx/ssl
      - ./gelweb/gelweb/static_files:/static
    depends_on:
      - web
      - redis
  web:
    image: gel2mdt_web:0.8.1
    restart: always
    build:
      context: .
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && gunicorn gelweb.wsgi --workers=9 -t 90 -b 0.0.0.0:8002"
    volumes:
      - .:/root/gel2mdt/
      - /home/genseqservadmin/.vep:/root/.vep
      - /home/genseqservadmin/NT_GEL2MDT/gel2mdt_resources:/root/gel2mdt_cache
    env_file:
      - /etc/gel2mdt/credentials
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=gel2mdt_db
      - MYSQL_USER=paddy
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - /home/genseqservadmin/NT_GEL2MDT/gel2mdt_resources/gel2mdt_db:/var/lib/mysql
    ports:
      - "3307:3306"
  celery:
    build: .
    restart: always
    image: gel2mdt_celery:0.8.1
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && celery -A gelweb worker -l info"
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - .:/root/gel2mdt/
      - /home/genseqservadmin/.vep:/root/.vep
      - /home/genseqservadmin/NT_GEL2MDT/gel2mdt_resources:/root/gel2mdt_cache
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    image: gel2mdt_celery-beat:0.8.1
    restart: always
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && rm -f celerybeat.pid && celery -A gelweb beat -l info"
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - .:/root/gel2mdt/
      - /home/genseqservadmin/.vep:/root/.vep
      - /home/genseqservadmin/NT_GEL2MDT/gel2mdt_resources:/root/gel2mdt_cache
    depends_on:
      - db
      - redis
  flower:
    build: .
    image: gel2mdt_flower:0.8.1
    restart: always
    env_file:
      - /etc/gel2mdt/credentials
    volumes:
      - .:/root/gel2mdt/
    command: bash -c "cd /root/gel2mdt/gelweb && celery flower -A gelweb --broker=redis://redis:6379 --port=5552"
    ports:
      - "5552:5552"
    depends_on:
      - db
      - redis
      - celery
      - celery-beat
  jupyter:
    image: gel2mdt_jupyter:0.8.1
    build: .
    restart: always
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && echo 'yes' | jupyter-lab --generate-config -y && cd /root/gel2mdt/gelweb && python manage.py shell_plus --notebook"
    volumes:
      - .:/root/gel2mdt/
      - /var/app/gel2mdt_resources:/root/gel2mdt_cache
    env_file:
      - /etc/gel2mdt/credentials
    ports:
      - "8891:8888"
    depends_on:
      - db
      - web
