# Generated by Django 2.0.1 on 2018-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0008_gelinterpretationreport_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerreport',
            name='action_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cancerreport',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancerreport',
            name='validated_assay_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cancerreport',
            name='variant_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proband',
            name='disease_subtype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proband',
            name='gmc',
            field=models.CharField(blank=True, choices=[('GOSH', 'GOSH'), ('MEH', 'MEH'), ('NHNN', 'NHNN'), ('RRV', 'RRV'), ('HHP', 'HHP'), ('RAL', 'RAL'), ('LNWH', 'LNWH'), ('UCLH', 'UCLH'), ('RNOH', 'RNOH'), ('WLGMC', 'WLGMC'), ('R1H', 'R1H'), ('RP4', 'RP4'), ('RAN', 'RAN'), ('RRV', 'RRV'), ('RT3', 'RT3'), ('Unknown', 'Unknown')], default='Unknown', max_length=255, null=True),
        ),
    ]
