# Generated by Django 2.0.1 on 2018-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0009_auto_20180423_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='proband',
            name='tumour_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancerreport',
            name='action_type',
            field=models.CharField(blank=True, choices=[('Not Significant', 'Not Significant'), ('No Validation Required', 'No Validation Required'), ('Validation Required', 'Validation Required'), ('Unable to Validate', 'Unable to Validate')], max_length=200, null=True),
        ),
    ]
