# Generated by Django 2.0.1 on 2018-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0010_auto_20180423_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proband',
            name='tumour_content',
        ),
        migrations.AddField(
            model_name='gelinterpretationreport',
            name='tumour_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
