# Generated by Django 2.0.1 on 2018-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0011_auto_20180423_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='proband',
            name='current_clinical_trial_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proband',
            name='currently_in_clinical_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proband',
            name='disease_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proband',
            name='disease_stage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proband',
            name='previous_testing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proband',
            name='previous_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proband',
            name='suitable_for_clinical_trial',
            field=models.BooleanField(default=False),
        ),
    ]
