# Generated by Django 2.0.1 on 2018-04-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0013_auto_20180426_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proband',
            name='case_sent',
        ),
        migrations.RemoveField(
            model_name='proband',
            name='mdt_status',
        ),
        migrations.RemoveField(
            model_name='proband',
            name='pilot_case',
        ),
        migrations.RemoveField(
            model_name='proband',
            name='status',
        ),
    ]
