# Generated by Django 2.0.1 on 2018-04-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0014_auto_20180426_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proband',
            name='episode',
        ),
    ]
