# Generated by Django 2.0.1 on 2018-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0015_remove_proband_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherstaff',
            options={'managed': True, 'verbose_name_plural': 'Other staff'},
        ),
        migrations.AddField(
            model_name='gelinterpretationreport',
            name='no_primary_findings',
            field=models.BooleanField(default=False),
        ),
    ]
