# Generated by Django 2.0.1 on 2018-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0016_auto_20180502_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancerreport',
            name='action_type',
            field=models.CharField(blank=True, choices=[('Predicts Therapeutic Response', 'Predicts Therapeutic Response'), ('Prognostic', 'Prognostic'), ('Defines diagnosis group', 'Defines diagnosis group'), ('Eligibility for trial', 'Eligibility for trial'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
