# Generated by Django 2.0.1 on 2018-05-25 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gel2mdt', '0017_auto_20180502_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='probandvariant',
            name='validation_datetime_set',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='probandvariant',
            name='validation_responsible_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probandvariant',
            name='validation_status',
            field=models.CharField(choices=[('U', 'Unknown'), ('A', 'Awaiting Validation'), ('K', 'Urgent Validation'), ('P', 'Passed Validation'), ('F', 'Failed Validation'), ('N', 'Not Required')], default='U', max_length=50),
        ),
    ]
