# Generated by Django 2.0.1 on 2018-07-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0018_auto_20180525_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(db_column='flag_name', max_length=255)),
            ],
            options={
                'db_table': 'PVFlag',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proband',
            name='disease_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gelinterpretationreport',
            name='max_tier',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='probandvariant',
            name='max_tier',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='probandvariant',
            name='validation_status',
            field=models.CharField(choices=[('U', 'Unknown'), ('A', 'Awaiting Validation'), ('K', 'Urgent Validation'), ('I', 'In Progress'), ('P', 'Passed Validation'), ('F', 'Failed Validation'), ('N', 'Not Required')], default='U', max_length=50),
        ),
        migrations.AlterField(
            model_name='rarediseasereport',
            name='classification',
            field=models.CharField(choices=[('NA', 'NA'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('A', 'Artefact')], db_column='classification', default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='pvflag',
            name='proband_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gel2mdt.ProbandVariant'),
        ),
    ]
