# Generated by Django 2.0.1 on 2018-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0019_auto_20180711_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelinterpretationreport',
            name='has_germline_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listupdate',
            name='reports_added',
            field=models.ManyToManyField(related_name='reports_added', to='gel2mdt.GELInterpretationReport'),
        ),
        migrations.AddField(
            model_name='listupdate',
            name='reports_updated',
            field=models.ManyToManyField(related_name='reports_updated', to='gel2mdt.GELInterpretationReport'),
        ),
        migrations.AddField(
            model_name='listupdate',
            name='sample_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
