# Generated by Django 2.0.1 on 2018-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0020_auto_20181008_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gel_id', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=255)),
                ('sample_type', models.CharField(choices=[('cancer', 'cancer'), ('raredisease', 'raredisease')], max_length=20)),
            ],
            options={
                'db_table': 'GELAlert',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gelinterpretationreport',
            name='case_code',
            field=models.CharField(blank=True, choices=[('REANALYSE', 'REANALYSE'), ('URGENT', 'URGENT')], max_length=20, null=True),
        ),
    ]
