# Generated by Django 2.0.1 on 2019-02-28 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gel2mdt', '0021_auto_20181026_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'CaseComment',
                'ordering': ['-time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreferredTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gel2mdt.Gene')),
                ('genome_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gel2mdt.ToolOrAssemblyVersion')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gel2mdt.Transcript')),
            ],
            options={
                'db_table': 'PreferredTranscript',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gelinterpretationreport',
            name='first_check',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_check_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gelinterpretationreport',
            name='second_check',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_check_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mdt',
            name='sent_to_clinician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proband',
            name='total_samples',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gelinterpretationreport',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gelinterpretationreport',
            name='case_code',
            field=models.CharField(blank=True, choices=[('REANALYSE', 'REANALYSE'), ('URGENT', 'URGENT'), ('SAMPLE', 'SAMPLE'), ('CLINGEN', 'CLINGEN'), ('RETURN', 'RETURN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proband',
            name='gmc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casecomment',
            name='interpretation_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gel2mdt.GELInterpretationReport'),
        ),
        migrations.AddField(
            model_name='casecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='preferredtranscript',
            unique_together={('gene', 'genome_assembly')},
        ),
    ]
