# Generated by Django 2.0.13 on 2019-08-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel2mdt', '0023_auto_20190429_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermissions',
            name='can_delete_mdt',
            field=models.BooleanField(default=False, help_text='Indicates whether the group can delete an MDT'),
        ),
        migrations.AlterField(
            model_name='gelinterpretationreport',
            name='case_code',
            field=models.CharField(blank=True, choices=[('REANALYSE', 'REANALYSE'), ('URGENT', 'URGENT'), ('SAMPLE', 'SAMPLE'), ('CLINGEN', 'CLINGEN'), ('DECEASED', 'DECEASED'), ('DNAREQ', 'DNAREQ'), ('RETURN', 'RETURN'), ('AUTHREQ', 'AUTHREQ'), ('ADDPANEL', 'ADDPANEL'), ('UNCONFIRMED', 'UNCONFIRMED')], max_length=20, null=True),
        ),
    ]
